name: Eunice Báez
favicon: null
layout_spectrum: 0.32129112957045436
typography_spectrum: 0.185295827453956
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f8fb'
    - '#3a463c'
    - '#487532'
    - '#6e9b58'
    - '#b0c791'
  brandStrength: 0.6875
  lightness: 0.7166705226991326
  saturation: 0.7562126591801643
  rhythmicContrast: 0.4311287410091609
purpose: []
